name: syndisco-exp
channels:
  - conda-forge
dependencies:
  - python
  - requests
  - beautifulsoup4
  - pandas
  - randomname
  - scikit-posthocs
  - statsmodels
  - rouge-score
  - seaborn
  - pip
  - pip:
      - syndisco